config/routes.rb
ImageCropping::Application.routes.draw do
  resources :uploads do 
    get :crop, on: :member
    get :resize, on: :member
  end
  root to: "welcome#index"
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :image
  has_attached_file :image
  RESIZE_THUMBNAILS = { thumb1: "30X30", thumb2: "60X60", thumb3: "90X90", thumb4: "120X120" }
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessible :crop_x, :crop_y, :crop_w, :crop_h

  validates :image, presence: true
  
  after_update :reprocess_image, if: :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def generate_thumbnails
    conn = Bunny.new(:automatically_recover => false)
    conn.start
    resize_channel = conn.create_channel
    x = resize_channel.direct("resize_router", durable: true, auto_delete: true)
    x.publish(resize_data.to_yaml, :routing_key => "resizer")  
    puts " [x] Sent Image For Resizing"
  end

  private

  def crop_data
    {
      path: "#{image.path}",
      height: "#{crop_h}",
      width: "#{crop_w}",
      crop_x: "#{crop_x}",
      crop_y: "#{crop_y}",
      type: "crop"
    }
  end

  def resize_data
    {
      path: "#{image.path}",
      styles: Upload::RESIZE_THUMBNAILS,
      type: "resize"
    }
  end

  def reprocess_image
    conn = Bunny.new(:automatically_recover => false)
    conn.start
    ch   = conn.create_channel
    x = ch.direct("crop_router1", durable: true, auto_delete: true)
    x.publish(crop_data.to_json, :routing_key => "cropper")
    puts " [x] Sent Image description"
    conn.close
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  
  before_filter :load_upload, only: [:update, :crop, :show, :destroy, :resize]

  def new 
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(params[:upload])
    if @upload.save
      flash[:notice] = "Successfully Uploaded"
      redirect_to crop_upload_path(@upload)
    else
      render "new"
    end
  end

  def show
  end

  def update
    if @upload.update_attributes(params[:upload])
      flash[:notice] = "Successfully updated Upload."
      redirect_to @upload
    else
      render :action => 'edit'
    end
  end

  def destroy
    if @upload.destroy
      flash[:notice] = "Successfully destroyed upload"
      redirect_to root_path
    else
      flash[:alert] = "Upload was not destroyed"
      redirect_to @upload
    end
  end

  def crop
  end

  def resize
    @upload.generate_thumbnails
    redirect_to @upload
  end

  private 

  def load_upload
    @upload = Upload.where(id: params[:id]).first
    unless @upload
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @upload = Upload.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageCropping</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <%- flash.each do |name, msg| -%>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <%- end -%> 
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.to_s.downcase %> from being saved:</h2>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/uploads/_form.html.erb
<%= form_for @upload, :html => { :multipart => true } do |f| %>
  <% if @upload.errors.any? %>
    <%= render "shared/errors", :object => @upload %>
  <% end %>
  <p>
    <b><%= f.label "Select An Image For Cropping..." %></b>
    <%= f.file_field :image %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/uploads/crop.html.erb
<h1> Crop Image </h1>
<% content_for :head do %>
  <%= stylesheet_link_tag "jquery.Jcrop" %>
  <%= javascript_include_tag "jquery.Jcrop" %>
  <script type="text/javascript">
  $(function(){
    $('#cropbox').Jcrop({
      onChange: updateCropCoords,
      onSelect: updateCropCoords,
      setSelect: [0,0,100,100],
      aspectRatio: Math.round($(this).width() / $(this).height())
    })
  })
  function updateCropCoords(coords){
    $('#crop_x').val(coords.x)
    $('#crop_y').val(coords.y)
    $('#crop_w').val(coords.w)
    $('#crop_h').val(coords.h)
  }
  </script>
<% end %>
<%= image_tag @upload.image.url, id: "cropbox" %>

<%= form_for @upload do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.text_field attribute, id: attribute, readonly: true %>
  <% end %>
  <%= f.submit "Crop" %>
<% end %>

<%= link_to "Back >>", @upload%>

app/views/uploads/new.html.erb
<h1>New Upload</h1>
<%= render :partial => 'form' %>

app/views/uploads/show.html.erb
<h1>Upload</h1>

<div>
  <h3> Original Image </h3>
  <p><%= image_tag @upload.image.url(:original) %></p>
</div>

<div>
  <h3> Cropped Image </h3>
  <p><%= image_tag @upload.image.url(:cropped) %></p>
</div>


<div>
  <h3> Resized Image </h3>
  <% Upload::RESIZE_THUMBNAILS.keys.each do |style| %>
    <p><%= image_tag @upload.image.url(style) %></p>
  <% end %>
</div>

<p>
  <%= link_to "Resize", resize_upload_path(@upload) %> |
  <%= link_to "Crop", crop_upload_path(@upload) %> |
  <%= link_to "Destroy", @upload, :confirm => 'Are you sure?', :method => :delete %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome To Image Cropping...</h1>

<%= render partial: "uploads/form" %>